name: Acceptance Tests

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  acceptance:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: go.mod
          cache: true
      - run: go test ./... -v -timeout 120m
        env:
          TF_ACC: "1"
          NGROK_API_KEY: ${{ secrets.NGROK_API_KEY }}
